<a href="https://colab.research.google.com/github/rauttanushka69-lgtm/Python-Basic-Projects./blob/master/Q1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [ ]:

import numpy as np

# Q1. Create 2D array of shape (5, 6) filled with random integers between 10 and 100
arr_2d = np.random.randint(10, 101, size=(5, 6))

print("----- : Array Properties -----")
print("Generated 2D Array:\n", arr_2d)
print("\nShape of ththee array:", arr_2d.shape)
print("Total number of elements (size):", arr_2d.size)
print("Data type (dtype):", arr_2d.dtype)

----- : Array Properties -----
Generated 2D Array:
 [[ 82  28  29  32  17  13]
 [ 53  88  24  68  40  69]
 [ 77  92  19  71  86  74]
 [ 68  67  79  78  37  57]
 [ 88  82  73  84 100  78]]

Shape of the array: (5, 6)
Total number of elements (size): 30
Data type (dtype): int64


In [ ]:
import numpy as np

# Q2. Generate 1D array of 20 random numbers between 1 and 50
arr_1d = np.random.randint(1, 51, size=20)

print("----- Q2: Statistical Methods - Basic -----")
print("Generated 1D Array:", arr_1d)

# Minimum value and its index
min_val = np.min(arr_1d)
min_index = np.argmin(arr_1d)
print("\nMinimum value:", min_val, "at index:", min_index)

# Maximum value and its index
max_val = np.max(arr_1d)
max_index = np.argmax(arr_1d)
print("Maximum value:", max_val, "at index:", max_index)

# Sum of all elements
print("Sum of all elements:", np.sum(arr_1d))

# Mean and Standard Deviation
print("Mean:", np.mean(arr_1d))
print("Standard Deviation:", round(np.std(arr_1d), 2))

----- Q2: Statistical Methods - Basic -----
Generated 1D Array: [ 6  4 33  5 41 28 15 41  6 47 29  9 31  3 13  4 20 41  6 16]

Minimum value: 3 at index: 13
Maximum value: 47 at index: 9
Sum of all elements: 398
Mean: 19.9
Standard Deviation: 14.68


In [ ]:
import numpy as np

# Q3. Create 4x5 matrix of random integers between 20 and 80
matrix_4x5 = np.random.randint(20, 81, size=(4, 5))

print("----- Q3: Statistical Methods on 2D Array -----")
print("Generated 4x5 Matrix:\n", matrix_4x5)

# For entire matrix
print("\n--- Entire Matrix Stats ---")
print("Minimum value:", np.min(matrix_4x5))
print("Maximum value:", np.max(matrix_4x5))
print("Sum of all elements:", np.sum(matrix_4x5))
print("Mean:", np.mean(matrix_4x5))
print("Standard Deviation:", round(np.std(matrix_4x5), 2))

# Sum of each row and each column
print("\nSum of each row:", matrix_4x5.sum(axis=1))
print("Sum of each column:", matrix_4x5.sum(axis=0))

----- Q3: Statistical Methods on 2D Array -----
Generated 4x5 Matrix:
 [[68 35 33 23 31]
 [77 66 73 49 34]
 [36 21 46 50 80]
 [27 30 43 49 63]]

--- Entire Matrix Stats ---
Minimum value: 21
Maximum value: 80
Sum of all elements: 934
Mean: 46.7
Standard Deviation: 18.14

Sum of each row: [190 299 233 212]
Sum of each column: [208 152 195 171 208]


In [ ]:
import numpy as np

# Q4. Create 1D array containing numbers from 1 to 24 using np.arange()
arr_1d_24 = np.arange(1, 25)

print("----- Q4: Reshape -----")
print("Original 1D Array:", arr_1d_24)
print("Shape:", arr_1d_24.shape)

# Optional: Reshape to 2D for better understanding
arr_reshaped = arr_1d_24.reshape(4, 6)  # 4*6 = 24
print("\nReshaped to 4x6 Array:\n", arr_reshaped)
print("New Shape:", arr_reshaped.shape)

----- Q4: Reshape -----
Original 1D Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Shape: (24,)

Reshaped to 4x6 Array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
New Shape: (4, 6)


In [ ]:
import numpy as np

# Create the given array
arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120]])

print("----- Q5: NumPy Indexing -----")
print("Original Array:\n", arr)

# 1. Extract first row
first_row = arr[0, :] # or arr[0]
print("\n1. First row:", first_row)

# 2. Extract last column
last_column = arr[:, -1] # or arr[:, 3]
print("2. Last column:", last_column)

# 3. Extract center 2x2 submatrix
# Center elements: 60, 70, 100, 110 -> rows 1,2 and cols 1,2
center_2x2 = arr[1:3, 1:3]
print("3. Center 2x2 submatrix:\n", center_2x2)

# 4. Extract all even numbers using boolean indexing
even_numbers = arr[arr % 2 == 0]
print("4. All even numbers:", even_numbers)

----- Q5: NumPy Indexing -----
Original Array:
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]

1. First row: [10 20 30 40]
2. Last column: [ 40  80 120]
3. Center 2x2 submatrix:
 [[ 60  70]
 [100 110]]
4. All even numbers: [ 10  20  30  40  50  60  70  80  90 100 110 120]


In [ ]:

import numpy as np

# Create 5x5 matrix of random integers between 1 and 100
matrix_5x5 = np.random.randint(1, 101, size=(5, 5))

print("----- Q6: Advanced Indexing -----")
print("Original 5x5 Matrix:\n", matrix_5x5)

# 1. Print the diagonal elements
diagonal = np.diag(matrix_5x5) # or matrix_5x5.diagonal()
print("\n1. Diagonal elements:", diagonal)

# 2. Print elements greater than 50
greater_than_50 = matrix_5x5[matrix_5x5 > 50]
print("2. Elements greater than 50:", greater_than_50)

# 3. Replace all elements less than 30 with 0
matrix_5x5[matrix_5x5 < 30] = 0
print("\n3. After replacing elements < 30 with 0:")

# 4. Print the modified array
print("4. Modified Array:\n", matrix_5x5)

----- Q6: Advanced Indexing -----
Original 5x5 Matrix:
 [[55 93 36 88  8]
 [48 33 26 29 38]
 [65 85 97  4 65]
 [13 10 73 12 91]
 [69 39 25 64 70]]

1. Diagonal elements: [55 33 97 12 70]
2. Elements greater than 50: [55 93 88 65 85 97 65 73 91 69 64 70]

3. After replacing elements < 30 with 0:
4. Modified Array:
 [[55 93 36 88  0]
 [48 33  0  0 38]
 [65 85 97  0 65]
 [ 0  0 73  0 91]
 [69 39  0 64 70]]


In [ ]:
import numpy as np

# Create two arrays
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

print("----- Q7: Arithmetic Operations -----")
print("Array a:", a)
print("Array b:", b)

# Perform and print operations
print("\nAddition a + b:", a + b)
print("Subtraction a - b:", a - b)
print("Multiplication a * b:", a * b)
print("Division a / b:", a / b)

# Element-wise power (**)
print("Element-wise power a ** b:", a ** b)

# Modulo operation (%)
print("Modulo a % b:", a % b)

----- Q7: Arithmetic Operations -----
Array a: [10 20 30 40]
Array b: [1 2 3 4]

Addition a + b: [11 22 33 44]
Subtraction a - b: [ 9 18 27 36]
Multiplication a * b: [ 10  40  90 160]
Division a / b: [10. 10. 10. 10.]
Element-wise power a ** b: [     10     400   27000 2560000]
Modulo a % b: [0 0 0 0]


In [ ]:
import numpy as np

# Create two 3x3 matrices
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[9,8,7],[6,5,4],[3,2,1]])

print("----- Q8: Matrix Multiplication -----")
print("Matrix A:\n", A)
print("\nMatrix B:\n", B)

# 1. Element-wise multiplication (*)
element_wise_mul = A * B
print("\n1. Element-wise multiplication A * B:\n", element_wise_mul)
# This multiplies corresponding elements: A[0,0]*B[0,0], A[0,1]*B[0,1], etc.

# 2. Matrix multiplication (@ or np.dot())
matrix_mul = A @ B # or np.dot(A, B)
print("\n2. Matrix multiplication A @ B:\n", matrix_mul)
# This is proper matrix multiplication: row of A dot column of B

print("\nDifference:")
print("* does element-wise multiplication of same positions")
print("@ or np.dot() does mathematical matrix multiplication using row-column rule")

----- Q8: Matrix Multiplication -----
Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]

1. Element-wise multiplication A * B:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]

2. Matrix multiplication A @ B:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Difference:
* does element-wise multiplication of same positions
@ or np.dot() does mathematical matrix multiplication using row-column rule


In [ ]:

import numpy as np

# Generate 6x6 matrix using np.random.randn() -> gives numbers from standard normal distribution
# These can be positive or negative
matrix_6x6 = np.random.randn(6, 6)

print("----- Q9: Combined Operations -----")
print("Generated 6x6 Matrix:\n", np.round(matrix_6x6, 2)) # rounded for clean display

# 1. Print shape, size, and dtype
print("\n1. Properties:")
print("Shape:", matrix_6x6.shape)
print("Size:", matrix_6x6.size)
print("Data type:", matrix_6x6.dtype)

# 2. Find index of maximum and minimum value
max_index = np.unravel_index(np.argmax(matrix_6x6), matrix_6x6.shape)
min_index = np.unravel_index(np.argmin(matrix_6x6), matrix_6x6.shape)
print("\n2. Index of max value:", max_index, "Value:", round(np.max(matrix_6x6), 2))
print(" Index of min value:", min_index, "Value:", round(np.min(matrix_6x6), 2))

# 3. Extract top-left 3x3 submatrix
top_left_3x3 = matrix_6x6[:3, :3]
print("\n3. Top-left 3x3 submatrix:\n", np.round(top_left_3x3, 2))

# 4. Replace all negative numbers with their absolute value
matrix_6x6[matrix_6x6 < 0] = np.abs(matrix_6x6[matrix_6x6 < 0])
print("\n4. Matrix after replacing negatives with absolute value:\n", np.round(matrix_6x6, 2))

# 5. Print mean of modified matrix
print("\n5. Mean of modified matrix:", round(np.mean(matrix_6x6), 4))

----- Q9: Combined Operations -----
Generated 6x6 Matrix:
 [[-0.44 -0.91  0.58 -2.61  0.1  -0.75]
 [ 1.47 -2.18 -0.72  2.29 -1.94  0.5 ]
 [-0.58 -1.45  0.2  -1.02  0.21  1.33]
 [ 1.16  1.4   2.2   0.1   1.61 -0.22]
 [ 1.61  2.61  0.71  1.39 -0.99 -0.17]
 [-1.17  0.83  0.13  1.06  0.95 -0.38]]

1. Properties:
Shape: (6, 6)
Size: 36
Data type: float64

2. Index of max value: (np.int64(4), np.int64(1)) Value: 2.61
 Index of min value: (np.int64(0), np.int64(3)) Value: -2.61

3. Top-left 3x3 submatrix:
 [[-0.44 -0.91  0.58]
 [ 1.47 -2.18 -0.72]
 [-0.58 -1.45  0.2 ]]

4. Matrix after replacing negatives with absolute value:
 [[0.44 0.91 0.58 2.61 0.1  0.75]
 [1.47 2.18 0.72 2.29 1.94 0.5 ]
 [0.58 1.45 0.2  1.02 0.21 1.33]
 [1.16 1.4  2.2  0.1  1.61 0.22]
 [1.61 2.61 0.71 1.39 0.99 0.17]
 [1.17 0.83 0.13 1.06 0.95 0.38]]

5. Mean of modified matrix: 1.0548


In [12]:
import numpy as np

print("----- Q10: Student Marks Analyzer -----")

# 1. Generate 2D array: 10 students x 5 subjects, marks between 30 and 100
np.random.seed(42) # For reproducible results, you can remove this line
student_marks = np.random.randint(30, 101, size=(10, 5))

# 2. Print the array
print("Student Marks Matrix [10 students x 5 subjects]:\n", student_marks)

# 3. For each student, calculate total marks and average
# axis=1 means row-wise operation, i.e., per student
total_marks = np.sum(student_marks, axis=1)
average_marks = np.mean(student_marks, axis=1)

print("\n--- Per Student Analysis ---")
for i in range(len(student_marks)):
    print(f"Student {i+1}: Total = {total_marks[i]}, Average = {round(average_marks[i], 2)}")

# 4. Find student with highest and lowest total marks using argmax/argmin
highest_idx = np.argmax(total_marks)
lowest_idx = np.argmin(total_marks)

print("\n--- Toppers & Lowest ---")
print(f"Highest Total: Student {highest_idx + 1} with {total_marks[highest_idx]} marks")
print(f"Lowest Total: Student {lowest_idx + 1} with {total_marks[lowest_idx]} marks")

# 5. Calculate overall class mean and standard deviation
class_mean = np.mean(student_marks)
class_std = np.std(student_marks)

print("\n--- Class Statistics ---")
print(f"Overall Class Mean: {round(class_mean, 2)}")
print(f"Overall Class Std Dev: {round(class_std, 2)}")

# 6. Extract marks of top 3 students based on total marks
# First, get indices of students sorted by total marks in descending order
sorted_indices = np.argsort(total_marks)[::-1] # [::-1] for descending
top_3_indices = sorted_indices[:3]
top_3_marks = student_marks[top_3_indices]

print("\n--- Top 3 Students ---")
print("Indices of Top 3:", top_3_indices + 1) # +1 for student number
print("Marks of Top 3 Students:\n", top_3_marks)

----- Q10: Student Marks Analyzer -----
Student Marks Matrix [10 students x 5 subjects]:
 [[ 81  44  90  50  53]
 [ 32  51  82  31  59]
 [ 67  31  93  89  50]
 [ 62  87  51  78  88]
 [ 71  89  44  91  91]
 [ 76  91  80  84  93]
 [ 32  80  36  50  68]
 [ 47  33  89  43  38]
 [ 82  31  89 100  73]
 [ 37  76  64  65  79]]

--- Per Student Analysis ---
Student 1: Total = 318, Average = 63.6
Student 2: Total = 255, Average = 51.0
Student 3: Total = 330, Average = 66.0
Student 4: Total = 366, Average = 73.2
Student 5: Total = 386, Average = 77.2
Student 6: Total = 424, Average = 84.8
Student 7: Total = 266, Average = 53.2
Student 8: Total = 250, Average = 50.0
Student 9: Total = 375, Average = 75.0
Student 10: Total = 321, Average = 64.2

--- Toppers & Lowest ---
Highest Total: Student 6 with 424 marks
Lowest Total: Student 8 with 250 marks

--- Class Statistics ---
Overall Class Mean: 65.82
Overall Class Std Dev: 21.48

--- Top 3 Students ---
Indices of Top 3: [6 5 9]
Marks of Top 3 Student