<a href="https://colab.research.google.com/github/rauttanushka69-lgtm/Python-Basic-Projects./blob/master/Task24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

# Load datasets
heart = pd.read_csv("heart.csv")
housing = pd.read_csv("Housing.csv")

print("Heart Dataset")
display(heart.head())

print("Housing Dataset")
display(housing.head())

Heart Dataset


,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0


Housing Dataset


,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

# ------------------ HEART DATASET ------------------

heart = heart.dropna()

# Convert categorical columns to numbers
le = LabelEncoder()

for col in heart.select_dtypes(include='object').columns:
    heart[col] = le.fit_transform(heart[col])

X_cls = heart.drop("HeartDisease", axis=1)
y_cls = heart["HeartDisease"]

scaler_cls = StandardScaler()
X_cls = scaler_cls.fit_transform(X_cls)

X_train_cls, X_test_cls, y_train_cls, y_test_cls = train_test_split(
    X_cls, y_cls, test_size=0.2, random_state=42
)

# ------------------ HOUSING DATASET ------------------

housing = housing.dropna()

for col in housing.select_dtypes(include='object').columns:
    housing[col] = le.fit_transform(housing[col])

X_reg = housing.drop("price", axis=1)
y_reg = housing["price"]

scaler_reg = StandardScaler()
X_reg = scaler_reg.fit_transform(X_reg)

X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(
    X_reg, y_reg, test_size=0.2, random_state=42
)

print("Preprocessing Completed Successfully")

Preprocessing Completed Successfully


In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Logistic Regression Model
lr = LogisticRegression()
lr.fit(X_train_cls, y_train_cls)

# Prediction
y_pred = lr.predict(X_test_cls)

# Results
print("Accuracy:", accuracy_score(y_test_cls, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test_cls, y_pred))

print("\nClassification Report:")
print(classification_report(y_test_cls, y_pred))

Accuracy: 0.8478260869565217

Confusion Matrix:
[[68  9]
 [19 88]]

Classification Report:
              precision    recall  f1-score   support

           0       0.78      0.88      0.83        77
           1       0.91      0.82      0.86       107

    accuracy                           0.85       184
   macro avg       0.84      0.85      0.85       184
weighted avg       0.85      0.85      0.85       184



In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Decision Tree Model
dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train_cls, y_train_cls)

# Prediction
y_pred = dt.predict(X_test_cls)

# Results
print("Accuracy:", accuracy_score(y_test_cls, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test_cls, y_pred))

print("\nClassification Report:")
print(classification_report(y_test_cls, y_pred))

Accuracy: 0.782608695652174

Confusion Matrix:
[[64 13]
 [27 80]]

Classification Report:
              precision    recall  f1-score   support

           0       0.70      0.83      0.76        77
           1       0.86      0.75      0.80       107

    accuracy                           0.78       184
   macro avg       0.78      0.79      0.78       184
weighted avg       0.79      0.78      0.78       184



In [ ]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# SVM Model
svm = SVC()
svm.fit(X_train_cls, y_train_cls)

# Prediction
y_pred = svm.predict(X_test_cls)

# Results
print("Accuracy:", accuracy_score(y_test_cls, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test_cls, y_pred))

print("\nClassification Report:")
print(classification_report(y_test_cls, y_pred))

Accuracy: 0.8641304347826086

Confusion Matrix:
[[66 11]
 [14 93]]

Classification Report:
              precision    recall  f1-score   support

           0       0.82      0.86      0.84        77
           1       0.89      0.87      0.88       107

    accuracy                           0.86       184
   macro avg       0.86      0.86      0.86       184
weighted avg       0.87      0.86      0.86       184



In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# KNN Model
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train_cls, y_train_cls)

# Prediction
y_pred = knn.predict(X_test_cls)

# Results
print("Accuracy:", accuracy_score(y_test_cls, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test_cls, y_pred))

print("\nClassification Report:")
print(classification_report(y_test_cls, y_pred))

Accuracy: 0.8478260869565217

Confusion Matrix:
[[68  9]
 [19 88]]

Classification Report:
              precision    recall  f1-score   support

           0       0.78      0.88      0.83        77
           1       0.91      0.82      0.86       107

    accuracy                           0.85       184
   macro avg       0.84      0.85      0.85       184
weighted avg       0.85      0.85      0.85       184



In [ ]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Naive Bayes Model
nb = GaussianNB()
nb.fit(X_train_cls, y_train_cls)

# Prediction
y_pred = nb.predict(X_test_cls)

# Results
print("Accuracy:", accuracy_score(y_test_cls, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test_cls, y_pred))

print("\nClassification Report:")
print(classification_report(y_test_cls, y_pred))

Accuracy: 0.842391304347826

Confusion Matrix:
[[65 12]
 [17 90]]

Classification Report:
              precision    recall  f1-score   support

           0       0.79      0.84      0.82        77
           1       0.88      0.84      0.86       107

    accuracy                           0.84       184
   macro avg       0.84      0.84      0.84       184
weighted avg       0.84      0.84      0.84       184



In [ ]:
import pandas as pd

results = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Decision Tree",
        "SVM",
        "KNN",
        "Naive Bayes"
    ],
    "Accuracy": [
        0.8478,
        0.7826,
        0.8641,
        0.8478,
        0.8424
    ]
})

print(results)

                 Model  Accuracy
0  Logistic Regression    0.8478
1        Decision Tree    0.7826
2                  SVM    0.8641
3                  KNN    0.8478
4          Naive Bayes    0.8424


In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

# Linear Regression Model
lr_reg = LinearRegression()
lr_reg.fit(X_train_reg, y_train_reg)

# Prediction
y_pred = lr_reg.predict(X_test_reg)

# R2 Score
lr_r2 = r2_score(y_test_reg, y_pred)
print("Linear Regression R2 Score:", lr_r2)

Linear Regression R2 Score: 0.6494754192267793


In [ ]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score

# Decision Tree Regressor
dt_reg = DecisionTreeRegressor(random_state=42)
dt_reg.fit(X_train_reg, y_train_reg)

# Prediction
y_pred = dt_reg.predict(X_test_reg)

# R2 Score
dt_r2 = r2_score(y_test_reg, y_pred)
print("Decision Tree R2 Score:", dt_r2)

Decision Tree R2 Score: 0.45898387163601084


In [ ]:
from sklearn.svm import SVR
from sklearn.metrics import r2_score

# SVR Model
svr = SVR()
svr.fit(X_train_reg, y_train_reg)

# Prediction
y_pred = svr.predict(X_test_reg)

# R2 Score
svr_r2 = r2_score(y_test_reg, y_pred)
print("SVR R2 Score:", svr_r2)

SVR R2 Score: -0.10156500412883829


In [ ]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import r2_score

# KNN Regressor
knn_reg = KNeighborsRegressor(n_neighbors=5)
knn_reg.fit(X_train_reg, y_train_reg)

# Prediction
y_pred = knn_reg.predict(X_test_reg)

# R2 Score
knn_r2 = r2_score(y_test_reg, y_pred)
print("KNN Regressor R2 Score:", knn_r2)

KNN Regressor R2 Score: 0.5743886156746412


In [ ]:
import pandas as pd

reg_results = pd.DataFrame({
    "Model": [
        "Linear Regression",
        "Decision Tree Regressor",
        "SVR",
        "KNN Regressor"
    ],
    "R2 Score": [
        0.6495,
        0.4590,
        -0.1016,
        0.5744
    ]
})

print(reg_results)

                     Model  R2 Score
0        Linear Regression    0.6495
1  Decision Tree Regressor    0.4590
2                      SVR   -0.1016
3            KNN Regressor    0.5744


In [ ]:
import joblib

# Save Best Classification Model (SVM)
joblib.dump(svm, "best_classification_model.pkl")

# Save Best Regression Model (Linear Regression)
joblib.dump(lr_reg, "best_regression_model.pkl")

# Save Scalers
joblib.dump(scaler_cls, "classification_scaler.pkl")
joblib.dump(scaler_reg, "regression_scaler.pkl")

print("All models and scalers saved successfully!")

All models and scalers saved successfully!


In [ ]:
%%writefile app.py

import streamlit as st
import joblib
import numpy as np

st.set_page_config(page_title="Session 24 AIML", layout="centered")

st.title("Session 24 - Multi Model Prediction App")

problem = st.selectbox(
    "Select Problem Type",
    ["Classification", "Regression"]
)

if problem == "Classification":

    model = joblib.load("best_classification_model.pkl")
    scaler = joblib.load("classification_scaler.pkl")

    st.header("Heart Disease Prediction")

    age = st.number_input("Age", 1, 100, 40)
    sex = st.selectbox("Sex", [0, 1])
    chest = st.selectbox("Chest Pain Type", [0, 1, 2, 3])
    bp = st.number_input("Resting BP", 80, 250, 120)
    chol = st.number_input("Cholesterol", 100, 600, 200)
    sugar = st.selectbox("Fasting Blood Sugar", [0, 1])
    ecg = st.selectbox("Rest ECG", [0, 1, 2])
    hr = st.number_input("Max Heart Rate", 60, 220, 150)
    angina = st.selectbox("Exercise Angina", [0, 1])
    oldpeak = st.number_input("Oldpeak", 0.0, 10.0, 1.0)
    slope = st.selectbox("ST Slope", [0, 1, 2])

    if st.button("Predict"):
        data = np.array([[age, sex, chest, bp, chol,
                          sugar, ecg, hr, angina,
                          oldpeak, slope]])

        data = scaler.transform(data)
        pred = model.predict(data)

        if pred[0] == 1:
            st.error("Heart Disease Detected")
        else:
            st.success("No Heart Disease")

Writing app.py


In [ ]:
!pip install streamlit

In [ ]:
!streamlit run app.py & npx localtunnel --port 8501

⠙⠹⠸⠼⠴

your url is: https://purple-eyes-fry.loca.lt
2026-07-28 09:38:05.838 Uvicorn server started on :::8501

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://34.170.106.145:8501

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
